# ============================================
# FILE: .github/workflows/cicd_template.yml
# Purpose: Simple CI/CD to deploy Databricks Asset Bundle to AWS Databricks workspace
# ============================================

name: Databricks CI/CD Simple Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Python (Databricks CLI depends on Python)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"
          pip install databricks-cli

      # Configure Databricks CLI
      - name: Configure Databricks CLI
        run: |
          databricks configure --token <<EOF
          https://dbc-d56de9ca-1926.cloud.databricks.com/
          dapi5fb62eab80e90679df4a1b68ad8a2be9
          EOF

      # Validate Databricks Asset Bundle
      - name: Validate DAB
        run: databricks bundle validate

      # Deploy Databricks Asset Bundle
      - name: Deploy DAB
        run: databricks bundle deploy --target dev

      # Run smoke tests (optional)
      - name: Smoke test
        run: |
          echo "Run some smoke tests here"
