# ============================================
# FILE: .github/workflows/deploy-databricks.yml
# Purpose: Generic Databricks Asset Bundle deployment using GitHub Actions Secrets
# ============================================

name: Deploy Databricks Bundle

on:
  workflow_dispatch:      # Manual run from Actions tab
  push:
    branches:
      - main              # Auto-run for every push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI v2
        uses: databricks/setup-cli@main

      - name: Deploy Databricks Asset Bundle
        env:
          DATABRICKS_HOST: https://dbc-d56de9ca-1926.cloud.databricks.com/
          DATABRICKS_TOKEN: dapi5fb62eab80e90679df4a1b68ad8a2be9
        run: |
          databricks bundle validate
          databricks bundle deploy --target dev --force-lock
